### ISSUE TITLE
CRA throws Cannot use 'in' operator to search for '__esModule' in dev mode

### ISSUE THREAD

**Issue by ocavue** [remirror/remirror-examples#21]
Run `pnpm dev` in the `with-create-react-app` example will cause the following error: 

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/24715727/192742325-cf064a37-49fe-47fc-817e-d6ce6094682f.png">

Remirror version: `remirror@2.0.7`.

**Comment by boomhauer94** [comment]
> Run `pnpm dev` in the `with-create-react-app` example will cause the following error: 
> 
> 
> 
> <img width="1470" alt="image" src="https://user-images.githubusercontent.com/24715727/192742325-cf064a37-49fe-47fc-817e-d6ce6094682f.png">
> 
> 
> 
> Remirror version: `remirror@2.0.7`.
